/**
 * GTNH-inspired recipes
 * for easier processing of some gem ores
 * as compared to electrolysis or GTM's default slurry recipes.
 *
 * This was motivated by gems being time-consuming to process
 * with little benefit in return.
 */

ServerEvents.recipes(event => {

    const gems = [
        // Corundums
        {
            name: "sapphire",
            products: [
                {name: "aluminium", chance: 9000},
                {name: "magnesium", chance: 1000},
                {name: "rutile", chance: 1000},
                {name: "iron", chance: 1500},
                {name: "vanadium", chance: 500},
            ]
        },
        {
            name: "green_sapphire",
            products: [
                {name: "aluminium", chance: 9000},
                {name: "beryllium", chance: 800},
                {name: "rutile", chance: 800},
                {name: "iron", chance: 2000},
                {name: "vanadium", chance: 500},
            ]
        },
        {
            name: "ruby",
            products: [
                {name: "aluminium", chance: 9000},
                {name: "chromium", chance: 8000},
                {name: "rutile", chance: 800},
                {name: "iron", chance: 1200},
                {name: "vanadium", chance: 250},
            ]
        },
        // Garnets
        {
            name: "pyrope",
            products: [
                {name: "aluminium", chance: 5000},
                {name: "magnesium", chance: 5000},
                {name: "silver", chance: 1000},
                {name: "chromium", chance: 1000},
                {name: "manganese", chance: 1000},
            ]
        },
        {
            name: "almandine",
            products: [
                {name: "aluminium", chance: 5000},
                {name: "iron", chance: 5000},
                {name: "gold", chance: 1000},
                {name: "rutile", chance: 800},
                {name: "vanadium", chance: 500},
            ]
        },
        {
            name: "spessartine",
            products: [
                {name: "aluminium", chance: 5000},
                {name: "manganese", chance: 5000},
                {name: "calcite", chance: 1500},
                {name: "magnesium", chance: 1500},
                {name: "tantalite", chance: 500},
            ]
        },
        {
            name: "grossular",
            products: [
                {name: "calcium", chance: 5000},
                {name: "aluminium", chance: 5000},
                {name: "chromium", chance: 1000},
                {name: "calcite", chance: 1500},
                {name: "vanadium", chance: 500},
            ]
        },
        // Mixed Garnets
        {
            name: "red_garnet",
            products: [
                {name: "aluminium", chance: 5000},
                {name: "magnesium", chance: 1000},
                {name: "iron", chance: 1500},
                {name: "manganese", chance: 2500},
            ]
        },
        {
            name: "yellow_garnet",
            products: [
                {name: "calcium", chance: 5000},
                {name: "iron", chance: 1500},
                {name: "aluminium", chance: 2500},
                {name: "chromium", chance: 1000},
            ]
        },
        // Other
        {name: "malachite"},
        {name: "olivine"}
    ]

    gems.forEach(gem => {
        event.recipes.gtceu.mixer(`${gem.name}_slurry_from_crushed_${gem.name}`)
            .itemInputs(`2x gtceu:crushed_${gem.name}_ore`)
            .itemInputs("gtceu:tiny_sodium_hydroxide_dust")
            .inputFluids("gtceu:hydrochloric_acid 1000", "gtceu:distilled_water 500")
            .outputFluids(`gtceu:${gem.name}_slurry 3000`)
            .duration(14 * 20)
            .EUt(100)

        event.recipes.gtceu.mixer(`${gem.name}_slurry_from_washed_${gem.name}`)
            .itemInputs(`2x gtceu:purified_${gem.name}_ore`)
            .itemInputs("gtceu:tiny_sodium_hydroxide_dust")
            .inputFluids("gtceu:hydrochloric_acid 1000", "gtceu:distilled_water 500")
            .outputFluids(`gtceu:${gem.name}_slurry 3000`)
            .duration(14 * 20)
            .EUt(100)

        // Autogenerated centrifuge recipes for every gem except those in the "other" category
        if(gem.products != null) {
            let centrifuge_recipe = event.recipes.gtceu.centrifuge(`${gem.name}_slurry_centrifuging`)
                .inputFluids(`gtceu:${gem.name}_slurry 3000`)
                .outputFluids("gtceu:diluted_hydrochloric_acid 1900")
                .duration(8 * 20)
                .EUt(GTValues.VHA[GTValues.MV])

            gem.products.forEach(product => {
                centrifuge_recipe.chancedOutput(`gtceu:${product.name}_dust`, product.chance, 0)
            })
        }
    })

    // Other centrifuging recipes
    event.recipes.gtceu.centrifuge("malachite_slurry_centrifuging")
        .inputFluids("gtceu:malachite_slurry 3000")
        .itemOutputs("2x gtceu:copper_dust")
        .chancedOutput("gtceu:calcite_dust", 1500, 0)
        .chancedOutput("gtceu:iron_dust", 1500, 0)
        .chancedOutput("gtceu:phosphate_dust", 1000, 0)
        .outputFluids("gtceu:diluted_hydrochloric_acid 1900")
        .duration(8 * 20)
        .EUt(GTValues.VHA[GTValues.MV])

    event.recipes.gtceu.centrifuge("olivine_slurry_centrifuging")
        .inputFluids("gtceu:olivine_slurry 3000")
        .itemOutputs("gtceu:magnesium_dust", "gtceu:iron_dust")
        .chancedOutput("gtceu:calcium_dust", 1500, 0)
        .chancedOutput("gtceu:aluminium_dust", 1000, 0)
        .chancedOutput("gtceu:nickel_dust", 1500, 0)
        .chancedOutput("gtceu:chromium_dust", 500, 0)
        .outputFluids("gtceu:diluted_hydrochloric_acid 1900")
        .duration(8 * 20)
        .EUt(GTValues.VHA[GTValues.MV])
})
