/**
 * Re-tiers the WEB Hub and WEB Receiver to late LuV - script 2 of 2.
 * - Replaces UV components with LuV components.
 */
ServerEvents.recipes(event => {
    event.remove({ id: "gtceu:assembly_line/pterb" })
    event.remove({ id: "gtceu:research_station/1x_gtceu_active_transformer" })
    event.remove({ id: "gtceu:research_station/1x_gtmutils_web_receiver" })
    event.remove({ id: "gtceu:assembly_line/web" })

    event.recipes.gtceu.assembly_line("pterb")
        .itemInputs("gtmutils:web_receiver")
        .itemInputs("32x gtceu:europium_plate")
        .itemInputs("2x gtceu:luv_sensor")
        .itemInputs("8x gtceu:luv_emitter")
        .itemInputs("4x gtceu:luv_field_generator")
        .itemInputs("2x #gtceu:circuits/zpm")
        .itemInputs("4x gtceu:europium_large_fluid_pipe")
        .itemInputs("16x gtceu:niobium_titanium_quadruple_cable")
        .itemInputs("8x gtceu:normal_laser_pipe")
        .inputFluids("gtceu:advanced_soldering_alloy 2304")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(1200)
        .addMaterialInfo(true)
        .itemOutputs("gtmutils:web_hub")
        ["scannerResearch(java.util.function.UnaryOperator)"](b => b
            .researchStack("gtmutils:web_receiver")
            .duration(2400)
            .EUt(GTValues.VA[GTValues.IV])
        )
    // Same as above but with Living Soldering Alloy
    event.recipes.gtceu.assembly_line("pterb/living_soldering_alloy")
        .itemInputs("gtmutils:web_receiver")
        .itemInputs("32x gtceu:europium_plate")
        .itemInputs("2x gtceu:luv_sensor")
        .itemInputs("8x gtceu:luv_emitter")
        .itemInputs("4x gtceu:luv_field_generator")
        .itemInputs("2x #gtceu:circuits/zpm")
        .itemInputs("4x gtceu:europium_large_fluid_pipe")
        .itemInputs("16x gtceu:niobium_titanium_quadruple_cable")
        .itemInputs("8x gtceu:normal_laser_pipe")
        .inputFluids("gtceu:living_soldering_alloy 1152")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(1200)
        .addMaterialInfo(true)
        .itemOutputs("gtmutils:web_hub")
        ["scannerResearch(java.util.function.UnaryOperator)"](b => b
            .researchStack("gtmutils:web_receiver")
            .duration(2400)
            .EUt(GTValues.VA[GTValues.IV])
        )

    event.recipes.gtceu.assembly_line("web")
        .itemInputs("gtceu:active_transformer")
        .itemInputs("8x gtceu:naquadah_plate")
        .itemInputs("4x gtceu:luv_sensor")
        .itemInputs("1x gtceu:luv_emitter")
        .itemInputs("1x #gtceu:circuits/zpm")
        .itemInputs("1x gtceu:naquadah_large_fluid_pipe")
        .itemInputs("4x gtceu:niobium_titanium_quadruple_cable")
        .itemInputs("8x gtceu:normal_laser_pipe")
        .inputFluids("gtceu:advanced_soldering_alloy 1152")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(1200)
        .addMaterialInfo(true)
        .itemOutputs("gtmutils:web_receiver")
        ["scannerResearch(java.util.function.UnaryOperator)"](b => b
            .researchStack("gtceu:active_transformer")
            .duration(2400)
            .EUt(GTValues.VA[GTValues.IV])
        )
    // Same as above but with Living Soldering Alloy
    event.recipes.gtceu.assembly_line("web/living_soldering_alloy")
        .itemInputs("gtceu:active_transformer")
        .itemInputs("8x gtceu:naquadah_plate")
        .itemInputs("4x gtceu:luv_sensor")
        .itemInputs("1x gtceu:luv_emitter")
        .itemInputs("1x #gtceu:circuits/zpm")
        .itemInputs("1x gtceu:naquadah_large_fluid_pipe")
        .itemInputs("4x gtceu:niobium_titanium_quadruple_cable")
        .itemInputs("8x gtceu:normal_laser_pipe")
        .inputFluids("gtceu:living_soldering_alloy 576")
        .EUt(GTValues.VA[GTValues.ZPM])
        .duration(1200)
        .addMaterialInfo(true)
        .itemOutputs("gtmutils:web_receiver")
        ["scannerResearch(java.util.function.UnaryOperator)"](b => b
            .researchStack("gtceu:active_transformer")
            .duration(2400)
            .EUt(GTValues.VA[GTValues.IV])
        )
})
