name: Bug Report
description: Create a report to help reproduce and fix the issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before creating an issue:
        If someone else has already reported the same issue, add to that discussion instead of making a new one.
        *Duplicate issues may be ignored or closed.*
        Please make sure the bug occurs on the latest release version.
        *Issues from older versions may be ignored or closed.*
        If the issue is with a specific mod, test to make sure that the issue does not occur just with that mod.
        *Bugs that afflict mods IN Monifactory instead of Monifactory itself may be ignored or closed.*
  - type: textarea
    id: summary
    attributes:
      label: Issue Summary
      description: Briefly explain your issue in a few plain sentences, e.g. "X has Y issue" "When I do X, Y happens instead of Z". You may copy and paste the issue title here if it provides enough detail.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Explain how to make the issue reoccur reliably. Issues that maintainers cannot reproduce may be ignored or closed.
      placeholder: |
        1. X recipe does not exist or has a bugged ingredient
        2. Y quest is inaccurate or is bugged
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
