
[miscellaneous]
	#Chance the anvil will break into chipped or damaged variant, or break completely after using. Value is set to 0.12 in vanilla.
	#Range: 0.0 ~ 1.0
	anvil_break_chance = 0.05
	#Solely renaming items in an anvil will never cause the anvil to break.
	risk_free_anvil_renaming = true
	#Edit name tags without cost nor anvil, simply by sneak + right-clicking.
	edit_name_tags_no_anvil = true
	#The naming field in anvils and the name tag gui will support formatting codes for setting custom text colors and styles.
	#Check out the Minecraft Wiki for all available formatting codes and their usage: https://minecraft.fandom.com/wiki/Formatting_codes#Usage
	renaming_supports_formatting = true
	#Allow using iron blocks to repair an anvil by one damage stage. Can be automated using dispensers.
	anvil_repairing = true

#Most default value represents vanilla behavior.
[costs]
	#Multiplier for each level of a rare enchantment being applied.
	#Range: > 1
	rare_enchantment_multiplier = 4
	#The additional cost in levels for combining an item with another item of the same kind when the first item is not fully repaired.
	#Range: > -2147483648
	repair_with_other_item_cost = 2
	#Multiplier for each level of a common enchantment being applied.
	#Range: > -2147483648
	common_enchantment_multiplier = 1
	#Multiplier for each level of a very rare enchantment being applied.
	#Range: > 1
	very_rare_enchantment_multiplier = 8
	#Multiplier for each level of a uncommon enchantment being applied.
	#Range: > 1
	uncommon_enchantment_multiplier = 2
	#Costs for applying enchantments from enchanted books are halved.
	halved_book_costs = true
	#The additional cost in levels for each valid repair material an item is repaired with in an anvil.
	#Range: > -2147483648
	repair_with_material_unit_cost = 1
	#Max cost of enchantment level allowed to be spent in an anvil. Every operation exceeding the limit will show as 'Too Expensive!' and will be disallowed.
	#If set to '-1' the limit is disabled.
	#Set to '40' enchantment levels in vanilla.
	#Range: > -1
	too_expensive_limit = -1
	#Renaming any item in an anvil no longer costs any enchantment levels at all. Can be restricted to only name tags.
	#Allowed Values: OFF, ALL_ITEMS, NAME_TAGS_ONLY
	free_renames = "ALL_ITEMS"

[prior_work_penalty]
	#FIXED: When renaming / repairing, ignore any prior work penalty on the item. Makes prior work penalty only relevant when new enchantments are added.
	#LIMITED: When renaming / repairing cost exceeds max anvil repair cost, limit cost just below max cost.
	#VANILLA: Renaming / repairing increase with prior work penalty and will no longer be possible when max cost is exceeded.
	#Allowed Values: VANILLA, FIXED, LIMITED
	rename_and_repair_costs = "FIXED"
	#Controls how working an item in the anvil multiple times affects the cost of future operations.
	#FIXED: A constant value is added every time the item is worked.
	#VANILLA: Penalty doubles every time an item is worked.
	#DISABLED: Penalty stays at 0 and does not increase.
	#Allowed Values: DISABLED, VANILLA, FIXED
	prior_work_penalty = "FIXED"
	#Prevents the prior work penalty from increasing when the item has only been renamed or repaired.
	penalty_free_renames_and_repairs = true
	#Constant to use when "prior_work_penalty" is set to "FIXED". Every subsequent operation will increase by this value in levels.
	#Range: > 1
	prior_work_penalty_constant = 4

