player = {}

[global]
	#Should use commands to build using this mod.
	useCommands = false
	#Should allow players to use this mod.
	allowUseMod = true
	#Should allow players to break blocks using this mod.
	allowBreakBlocks = true
	#Should allow players to place blocks using this mod.
	allowPlaceBlocks = true
	#Should allow players to interact blocks using this mod.
	allowInteractBlocks = true
	#Should allow players to copy and paste structures using this mod.
	allowCopyPasteStructure = true
	#Should allow players to break blocks with proper tools only in survival mode.
	useProperToolsOnly = true
	#The maximum distance a player can reach when building using this mod. 
	#Range: 0 ~ 32767
	maxReachDistance = 128
	#The maximum block volume a player can break at once when building using this mod. 
	#Range: 0 ~ 1000000
	maxBlockBreakVolume = 10000
	#The maximum block volume a player can place at once when building using this mod. 
	#Range: 0 ~ 1000000
	maxBlockPlaceVolume = 10000
	#The maximum block volume a player can interact at once when building using this mod. 
	#Range: 0 ~ 1000000
	maxBlockInteractVolume = 10000
	#The maximum structure volume a player can copy and paste at once when building using this mod. 
	#Range: 0 ~ 1000000
	maxStructureCopyPasteVolume = 10000
	#The list of items that players are allowed to break/place/interact when building using this mod. 
	#If the whitelist is empty, all items are allowed. 
	#If the whitelist is not empty, only the items in the whitelist are allowed. 
	#The value must be a list of item resource locations like ["minecraft:stone", "minecraft:dirt"].
	whitelistedItems = []
	#The list of items that players are not allowed to break/place/interact when building using this mod. 
	#If the blacklist is empty, no items are not allowed. 
	#If an item exists both in the blacklist and the whitelist, it will not be allowed. 
	#The value must be a list of item resource locations like ["minecraft:stone", "minecraft:dirt"].
	blacklistedItems = []
