features:
  # Whether the Sterile Cleaning Maintenance Hatch is enabled.
  sterileHatchEnabled: false

  # Whether the 64A energy converters are enabled.
  converters64aEnabled: true

  # Whether the Omni-breaker is enabled.
  omnibreakerEnabled: true

  # What tier the Omni-breaker is, if enabled. (ULV = 0, LV = 1, MV = 2, ...)
  # (Unless the default recipe is overridden, can only support LV to IV!)
  omnibreakerTier: 5

  # The energy capacity of the Omni-breaker.
  omnibreakerEnergyCapacity: 40960000

