values:
  # The exponent used each time the Omnic Synthesizer performs an operation.
  omnicSynthesizerExponent: 1.557

  # Minimum multiplier to antimatter generation (inclusive).
  antimatterRandomMinInclusive: 0.5

  # Maximum multiplier to antimatter generation (exclusive).
  antimatterRandomMaxExclusive: 2.0

  # Whether the microminer is returned upon a microverse reaching zero integrity.
  microminerReturnedOnZeroIntegrity: true

  # The efficiency multiplier for the sculk vat. Would make it this many times less efficient at empty/full compared to half.
  sculkVatEfficiencyMultiplier: 8.0

  # Fluid ID for Liquid Experience for the Sculk Vat.
  sculkVatExperienceFluidID: enderio:xp_juice

