colors:
  # Add custom formatting codes here.
  # Format: 'char:hex' (e.g., 'z:BF00FF')
  customColors:
    - z:BF00FF
    - t:00FF80
    - s:0B585C

  # Format: 'char:colorSpeed:moveSpeed:movementId:hex1,hex2...'
  # Example: 'w:1.0:0.5:wave:rainbow'
  # Movement IDs: wave, shake, pulse, static_rainbow, glitch, discord, breath, stretch, none
  # Discord is the effect you see on servers with boosts, that smooth gradient. This one needs exactly two hex codes to work properly.
  customGradients:
    - w:1.0:1.0:wave:rainbow
    - p:1.0:2.0:pulse:FF0000,990000
    - *:1.5:0.0:static_rainbow:rainbow
    - g:1.0:3.0:glitch:00FF00,005500
    - y:2.5:0.0:none:FF0000,FFFF00,00FF00
    - ^:0.0:0.0:discord:BF00FF,FFB7C5
    - #:0.0:2.0:breath:FF00FF
    - %:0.0:2.0:stretch:FF00FF

