
#General settings
[profiles]
	#A list of dimensions with associated city generation profiles (format <dimensionid>=<profilename>
	dimensionsWithProfiles = ["lostcities:lostcity=default"]
	#If true then a different heightmap generation algorithm is used which should be slightly more efficient. Be careful with this as it might not be 100% compatible with some other terrain generation mods!
	optimizedHeightmap = false
	#The size of the chunk grid used for heightmap sampling. Default is 1 which means every chunk is sampled. Higher values will sample less chunks and thus be faster but also less accurate
	#Range: 1 ~ 100
	heightSampleSize = 3

