/**
 * Peek and associated chemicals
 */
ServerEvents.recipes(event => {
    // Peek precursors
    event.recipes.gtceu.chemical_reactor("nitrotoluene")
        .inputFluids("gtceu:toluene 1000", "gtceu:nitric_acid 1000")
        .outputFluids("gtceu:nitrotoluene 1000", "gtceu:hydrogen 2000")
        .duration(100)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor("analine")
        .notConsumable("gtceu:palladium_dust")
        .inputFluids("gtceu:nitrobenzene 1000", "gtceu:hydrogen 6000")
        .outputFluids("gtceu:analine 1000", "minecraft:water 2000")
        .duration(100)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor("nitrous_acid")
        .inputFluids("gtceu:hydrogen 1000", "gtceu:nitrogen 1000", "gtceu:oxygen 2000")
        .outputFluids("gtceu:nitrous_acid 1000")
        .circuit(6)
        .duration(160)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor("fluoroboric_acid")
        .itemInputs("gtceu:boron_dust")
        .inputFluids("gtceu:hydrogen 1000", "gtceu:fluorine 4000")
        .outputFluids("gtceu:fluoroboric_acid")
        .circuit(1)
        .duration(1800)
        .EUt(GTValues.VA[GTValues.UV])

    event.recipes.gtceu.chemical_reactor("fluoroboric_acid_recycle")
        .itemInputs("gtceu:boron_trifluoride")
        .inputFluids("gtceu:hydrofluoric_acid 1000")
        .outputFluids("gtceu:fluoroboric_acid")
        .duration(100)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor("p-toluidine")
        .notConsumable("gtceu:palladium_dust")
        .inputFluids("gtceu:nitrotoluene 1000", "gtceu:hydrogen 2000")
        .outputFluids("gtceu:p-toluidine 1000", "gtceu:oxygen 2000")
        .duration(160)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.chemical_reactor("4-fluorotoluene")
        .inputFluids("gtceu:p-toluidine 1000", "gtceu:hydrofluoric_acid 1000")
        .outputFluids("gtceu:4-fluorotoluene", "gtceu:ammonia 1000")
        .duration(200)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.mixer("fluorotoluene_mixture")
        .inputFluids("gtceu:4-fluorotoluene 1000", "gtceu:chlorine 6000")
        .outputFluids("gtceu:fluorotoluene_mixture 1000")
        .duration(20)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.laser_engraver("fluorotoluene_mixture_activation")
        .notConsumable("gtceu:black_glass_lens")
        .itemInputs(Item.of("gtceu:fluid_cell", '{Fluid:{Amount:1000,FluidName:"gtceu:fluorotoluene_mixture"}}').weakNBT())
        .itemOutputs(Item.of("gtceu:fluid_cell", '{Fluid:{Amount:1000,FluidName:"gtceu:activated_fluorotoluene_mixture"}}').weakNBT())
        .duration(600)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.canner("fluorotoluene_mixture_separation")
        .itemInputs(Item.of("gtceu:fluid_cell", '{Fluid:{Amount:1000,FluidName:"gtceu:activated_fluorotoluene_mixture"}}').weakNBT())
        .itemOutputs("gtceu:fluid_cell")
        .outputFluids("gtceu:activated_fluorotoluene_mixture 1000")
        .duration(60)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.centrifuge("4-fluorotrichlorotoluene")
        .inputFluids("gtceu:activated_fluorotoluene_mixture 1000")
        .outputFluids("gtceu:4-fluorotrichlorotoluene 1000", "gtceu:hydrochloric_acid 3000")
        .duration(400)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor("4-fluorobenzoyl_chloride")
        .notConsumable("gtceu:activated_carbon_dust")
        .inputFluids("gtceu:4-fluorotrichlorotoluene 1000", "minecraft:water 1000")
        .outputFluids("gtceu:4-fluorobenzoyl_chloride 1000", "gtceu:hydrochloric_acid 2000")
        .duration(240)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.chemical_reactor("benzenediazonium_chloride")
        .inputFluids("gtceu:analine 1000", "gtceu:hydrochloric_acid 1000", "gtceu:nitrous_acid 1000")
        .outputFluids("gtceu:benzenediazonium_chloride 1000", "minecraft:water 2000")
        .duration(240)
        .EUt(GTValues.VA[GTValues.IV])
})
