/**
 * Peek and associated chemicals
 */
ServerEvents.recipes(event => {
    // Peek precursors
    event.recipes.gtceu.chemical_reactor("nitrotoluene")
        .inputFluids("gtceu:toluene 1000", "gtceu:nitric_acid 1000")
        .outputFluids("gtceu:nitrotoluene 1000", "gtceu:hydrogen 2000")
        .duration(100)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor("analine")
        .notConsumable("gtceu:palladium_dust")
        .inputFluids("gtceu:nitrobenzene 1000", "gtceu:hydrogen 6000")
        .outputFluids("gtceu:analine 1000", "minecraft:water 2000")
        .duration(100)
        .EUt(GTValues.VA[GTValues.EV])

    event.recipes.gtceu.chemical_reactor("nitrous_acid")
        .inputFluids("gtceu:hydrogen 1000", "gtceu:nitrogen 1000", "gtceu:oxygen 2000")
        .outputFluids("gtceu:nitrous_acid 1000")
        .circuit(6)
        .duration(160)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.large_chemical_reactor("fluoroboric_acid")
        .itemInputs("gtceu:boron_dust")
        .inputFluids("gtceu:hydrofluoric_acid 4000", "gtceu:hydrogen_peroxide 1500")
        .outputFluids("gtceu:fluoroboric_acid 1000", "minecraft:water 3000")
        .duration(1800)
        .EUt(GTValues.VA[GTValues.UV])

    event.recipes.gtceu.chemical_reactor("fluoroboric_acid_recycle")
        .inputFluids("gtceu:boron_trifluoride 1000", "gtceu:hydrofluoric_acid 1000")
        .outputFluids("gtceu:fluoroboric_acid")
        .duration(100)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.large_chemical_reactor("p-toluidine")
        .notConsumable("gtceu:palladium_dust")
        .inputFluids("gtceu:nitrotoluene 1000", "gtceu:hydrogen 2000")
        .outputFluids("gtceu:p-toluidine 1000", "gtceu:oxygen 2000")
        .duration(160)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.chemical_reactor("4-fluorotoluene")
        .inputFluids("gtceu:p-toluidine 1000", "gtceu:hydrofluoric_acid 1000")
        .outputFluids("gtceu:4-fluorotoluene", "gtceu:ammonia 1000")
        .duration(200)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.mixer("fluorotoluene_mixture")
        .inputFluids("gtceu:4-fluorotoluene 1000", "gtceu:chlorine 6000")
        .outputFluids("gtceu:fluorotoluene_mixture 1000")
        .duration(20)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.canner("fluorotoluene_mixture_canning")
        .itemInputs("gtceu:fluid_cell")
        .inputFluids("gtceu:fluorotoluene_mixture 1000")
        .itemOutputs(Item.of("gtceu:fluid_cell", '{Fluid:{Amount:1000,FluidName:"gtceu:fluorotoluene_mixture"}}'))
        .duration(16)
        .EUt(4)

    event.recipes.gtceu.laser_engraver("fluorotoluene_mixture_activation")
        .notConsumable("gtceu:black_glass_lens")
        .itemInputs(Item.of("gtceu:fluid_cell", '{Fluid:{Amount:1000,FluidName:"gtceu:fluorotoluene_mixture"}}').weakNBT())
        .itemOutputs(Item.of("gtceu:fluid_cell", '{Fluid:{Amount:1000,FluidName:"gtceu:activated_fluorotoluene_mixture"}}').weakNBT())
        .duration(600)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.canner("fluorotoluene_mixture_uncanning")
        .itemInputs(Item.of("gtceu:fluid_cell", '{Fluid:{Amount:1000,FluidName:"gtceu:activated_fluorotoluene_mixture"}}').weakNBT())
        .itemOutputs("gtceu:fluid_cell")
        .outputFluids("gtceu:activated_fluorotoluene_mixture 1000")
        .duration(16)
        .EUt(4)

    event.recipes.gtceu.centrifuge("4-fluorotrichlorotoluene")
        .inputFluids("gtceu:activated_fluorotoluene_mixture 1000")
        .outputFluids("gtceu:4-fluorotrichlorotoluene 1000", "gtceu:hydrochloric_acid 3000")
        .duration(400)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.large_chemical_reactor("4-fluorobenzoyl_chloride")
        .notConsumable("gtceu:activated_carbon_dust")
        .inputFluids("gtceu:4-fluorotrichlorotoluene 1000", "minecraft:water 1000")
        .outputFluids("gtceu:4-fluorobenzoyl_chloride 1000", "gtceu:hydrochloric_acid 2000")
        .duration(240)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.chemical_reactor("benzenediazonium_chloride")
        .inputFluids("gtceu:analine 1000", "gtceu:hydrochloric_acid 1000", "gtceu:nitrous_acid 1000")
        .outputFluids("minecraft:water 2000")
        .itemOutputs("14x gtceu:benzenediazonium_chloride_dust")
        .duration(240)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor("benzenediazonium_fluoroborate")
        .itemInputs("14x gtceu:benzenediazonium_chloride_dust")
        .inputFluids("gtceu:fluoroboric_acid 1000")
        .outputFluids("gtceu:hydrochloric_acid 1000")
        .itemOutputs("18x gtceu:benzenediazonium_fluoroborate_dust")
        .duration(320)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.arc_furnace("fluorobenzene")
        .itemInputs("18x gtceu:benzenediazonium_fluoroborate_dust")
        .inputFluids("gtceu:argon 200")
        .outputFluids("gtceu:fluorobenzene_gas_mixture 1000")
        .duration(300)
        .EUt(GTValues.VA[GTValues.HV])

    event.recipes.gtceu.mixer("4-4-difluorobenzophenone")
        .inputFluids("gtceu:fluorobenzene 1000", "gtceu:4-fluorobenzoyl_chloride 1000")
        .itemOutputs("24x gtceu:4-4-difluorobenzophenone_dust")
        .outputFluids("gtceu:hydrochloric_acid 1000")
        .duration(300)
        .EUt(GTValues.VA[GTValues.ZPM])

    event.recipes.gtceu.chemical_reactor("hydroquinone")
        .notConsumable("1x gtceu:rutile_dust")
        .inputFluids("gtceu:phenol 1000", "gtceu:hydrogen_peroxide 1000")
        .itemOutputs("14x gtceu:hydroquinone_dust")
        .outputFluids("minecraft:water 1000")
        .duration(240)
        .EUt(GTValues.VA[GTValues.MV])

    event.recipes.gtceu.chemical_reactor("sulfolene")
        .inputFluids("gtceu:sulfur_dioxide 1000", "gtceu:butadiene 1000")
        .outputFluids("gtceu:sulfolene 1000")
        .duration(300)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.chemical_reactor("sulfolane")
        .notConsumable("gtceu:nickel_dust")
        .inputFluids("gtceu:sulfolene 1000", "gtceu:hydrogen 2000")
        .outputFluids("gtceu:sulfolane 1000")
        .circuit(7)
        .duration(300)
        .EUt(GTValues.VA[GTValues.IV])

    event.recipes.gtceu.large_chemical_reactor("polyether_ether_ketone")
        .chancedFluidInput("gtceu:sulfolane 500", 700, 0)
        .itemInputs("24x gtceu:4-4-difluorobenzophenone_dust", "14x gtceu:hydroquinone_dust", "5x gtceu:soda_ash_dust")
        .itemOutputs("4x gtceu:sodium_fluoride_dust")
        .outputFluids("gtceu:polyether_ether_ketone 1000", "gtceu:carbon_dioxide 1000", "minecraft:water 1000")
        .duration(400)
        .EUt(GTValues.VA[GTValues.ZPM])

    event.recipes.gtceu.electrolyzer("fluorobenzene_mixture_decomposition")
        .inputFluids("gtceu:fluorobenzene_gas_mixture 1000")
        .outputFluids("gtceu:nitrogen 2000", "gtceu:boron_trifluoride 1000", "gtceu:fluorobenzene 1000")
        .duration(100)
        .EUt(GTValues.VA[GTValues.IV])
})
