/**
 * Sculk Bioalloy processing line
 */
ServerEvents.recipes(event => {
    event.recipes.gtceu.mixer("experience_attuned_dust")
        .itemInputs("7x gtceu:amethyst_dust", "2x gtceu:dark_soularium_dust", "4x gtceu:lapis_dust")
        .itemOutputs("gtceu:experience_attuned_dust")
        .duration(100)
        .EUt(GTValues.VA[GTValues.LuV])

    event.remove({ id: "gtceu:extractor/extract_experience_attuned_dust"})
    event.recipes.gtceu.chemical_bath("experience_attuned_vapor")
        .itemInputs("gtceu:experience_attuned_dust")
        .inputFluids("gtceu:americium_plasma 144")
        .itemOutputs("gtceu:americium_dust")
        .outputFluids("gtceu:experience_attuned 144")
        .duration(100)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.autoclave("manyullyn_based_trellis_microstructure")
        .itemInputs("gtceu:manyullyn_dust", "gtceu:carbon_fiber_mesh")
        .inputFluids("gtceu:nether_star 144")
        .itemOutputs("kubejs:manyullyn_based_trellis_microstructure")
        .duration(100)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.vacuum_freezer("experience_attuned_microstructure")
        .itemInputs("kubejs:manyullyn_based_trellis_microstructure")
        .inputFluids("gtceu:experience_attuned 144")
        .itemOutputs("kubejs:experience_attuned_microstructure")
        .duration(100)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.mixer("experience_concentrate")
        .itemInputs("3x enderio:withering_powder")
        .inputFluids("enderio:xp_juice 1500", "gtceu:bio_diesel")
        .outputFluids("kubejs:experience_concentrate")
        .duration(100)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.large_chemical_reactor("experience_rich_growth_medium")
        .itemInputs("4x gtceu:potassium_cyanide_dust")
        .inputFluids("kubejs:experience_concentrate", "gtceu:sterilized_growth_medium 500")
        .outputFluids("kubejs:experience_rich_growth_medium")
        .duration(100)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.autoclave("experience_saturated_microstructure")
        .itemInputs("kubejs:experience_attuned_microstructure")
        .inputFluids("kubejs:experience_rich_growth_medium")
        .itemOutputs("kubejs:experience_saturated_microstructure")
        .duration(100)
        .EUt(GTValues.VA[GTValues.LuV])

    event.recipes.gtceu.sculk_vat("hadal_sculk_growing")
        .itemInputs("kubejs:hadal_shard", "10x gtceu:echo_shard_dust")
        .inputFluids("gtceu:sculk 4000")
        .outputFluids("kubejs:hadal_sculk 4000")
        .xpRange(120000, 128000)
        .duration(100)
        .EUt(GTValues.VA[GTValues.LuV])
        .cleanroom(CleanroomType.CLEANROOM)

    event.recipes.gtceu.discharger("amalgamated_sculk")
        .itemInputs("kubejs:experience_saturated_microstructure", Item.of("kubejs:hadal_energy_core", "{Damage:8000000}").weakNBT())
        .inputFluids("kubejs:hadal_sculk")
        .itemOutputs("kubejs:amalgamated_sculk")
        .duration(10)

    event.recipes.gtceu.sculk_vat("bioalloy_growing")
        .itemInputs("kubejs:amalgamated_sculk", "gtceu:blue_alloy_dust")
        .inputFluids("kubejs:experience_concentrate 2000", "gtceu:lead 288", "gtceu:lutetium 576")
        .outputFluids("gtceu:sculk_bioalloy 2000")
        .xpRange(64000, 88000)
        .duration(100)
        .EUt(GTValues.VA[GTValues.LuV])
        .cleanroom(CleanroomType.CLEANROOM)
})
