
[lithium]
	#Ore generation settings for lithium
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

[platinum]
	#Ore generation settings for platinum
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 0
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

[thorium]
	#Ore generation settings for thorium
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

[tin]
	#Ore generation settings for tin
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = 4
	#Range: -64 ~ 255
	max_height = 60
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

[magnesium]
	#Ore generation settings for magnesium
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

[silver]
	#Ore generation settings for silver
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

[cobalt]
	#Ore generation settings for cobalt
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

[uranium]
	#Ore generation settings for uranium
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

[zinc]
	#Ore generation settings for zinc
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = 4
	#Range: -64 ~ 255
	max_height = 60
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

[boron]
	#Ore generation settings for boron
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = -60
	#Range: -64 ~ 255
	max_height = 60
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

[lead]
	#Ore generation settings for lead
	register = true
	#Range: 0 ~ 64
	vein_size = 7
	#Range: -64 ~ 255
	min_height = 4
	#Range: -64 ~ 255
	max_height = 60
	gen_dimensions = ["minecraft:overworld", "nuclearcraft:wasteland"]

