
#Settings for Radiation
[radiation]
	#If radiation is enabled.
	enabled = false
	#General background radiation everywhere (pRad).
	#Total radiation = background_radiation + dimension_radiation + chunk_radiation + in-game exposure
	#Range: 0 ~ 10000
	background_radiation = 50
	#How fast contamination decays (pRad/s).
	#Range: 1000 ~ 10000
	decay_speed = 1500
	#How fast contamination decays in player's body (uRad/s).
	#Range: 1 ~ 5000
	decay_speed_for_player = 50
	#Rate at which player gets radiation dose.
	#Range: 0.0 ~ 5.0
	gain_speed_for_player = 0.015
	#List of items what cleans player radiation when used (pRad). Format: item_id|radiation
	radiation_removal_items = ["minecraft:golden_carrot|500000", "minecraft:golden_apple|20000000", "minecraft:enchanted_golden_apple|100000000", "nuclearcraft:dominos|50000000", "nuclearcraft:moresmore|100000000", "nuclearcraft:evenmoresmore|200000000", "nuclearcraft:radaway|300000000"]
	#List of items what have radiation (pRad). Format: item_id|radiation
	items_radiation = ["nuclearcraft:spaxelhoe_thorium|50000", "mekanism:pellet_polonium|4000000", "mekanism:pellet_plutonium|2500000", "mekanism:reprocessed_fissile_fragment|1800000"]
	#List of armor items and default shielding lvl. Format: item_id|radiation
	armor_shielding = ["mekanism:hazmat_mask|3", "mekanism:hazmat_gown|5", "mekanism:hazmat_pants|4", "mekanism:hazmat_boots|3", "mekanism:mekasuit_helmet|5", "mekanism:mekasuit_bodyarmor|5", "mekanism:mekasuit_pants|5", "mekanism:mekasuit_boots|5", "nuclearcraft:hazmat_mask|3", "nuclearcraft:hazmat_chest|5", "nuclearcraft:hazmat_pants|4", "nuclearcraft:hazmat_boots|3", "nuclearcraft:hev_helmet|5", "nuclearcraft:hev_chest|7", "nuclearcraft:hev_pants|6", "nuclearcraft:hev_boots|5"]
	#Natural radiation per biome: uRad
	#Format: biome_id|radiation
	biome_radiation = ["nuclearcraft:wasteland|2000", "minecraft:nether_wastes|500"]
	#Natural radiation per dimension: uRad
	#Format: dim_id|radiation
	dimension_radiation = ["nuclearcraft:wasteland|200000", "minecraft:the_nether|1000"]
	#Interval between radiation updates in ticks. 20 ticks = 1 second.
	#Bigger interval - less lag, but less accurate radiation decay.
	#Range: 2 ~ 1000
	update_interval = 40
	#NC radiation sources will generate mekanism radiation and wise-versa.
	#You can disable mekanism radiation, but radiation sources in mekanism still will generate NC radiation.
	#You can disable NC radiation, but NC radiation sources still will generate mekanism radiation.
	mekanism_radiation_integration = true

