// priority: 2
/**
 * Registration of custom chemical elements
 */

// Elements
GTCEuStartupEvents.registry("gtceu:element", event => {
    event.create("cryococcus")
        .protons(149)
        .neutrons(264)
        .symbol("Cy*")
    event.create("cryolobus")
        .protons(149)
        .neutrons(234)
        .symbol("Cy")
    event.create("crystal_matrix")
        .protons(6)
        .neutrons(6)
        .symbol("C*")
    event.create("dilithium")
        .protons(119)
        .neutrons(229)
        .symbol("Dl")
    event.create("eltz")
        .protons(15)
        .neutrons(15)
        .symbol("Ez")
    event.create("hyperdegenerate_matter")
        .protons(250)
        .neutrons(1000)
        .symbol("Ω")
    event.create("infinity")
        .protons(168)
        .neutrons(316)
        .symbol("∞")
    event.create("mana")
        .symbol("ᛗ")
    event.create("meta_null")
        .protons(0)
        .neutrons(0)
        .symbol("∅")
    event.create("monium")
        .protons(169)
        .neutrons(317)
        .symbol("Mu")
    event.create("necrosiderite")
        .protons(67)
        .neutrons(-26)
        .symbol("Ns")
    event.create("omnium")
        .protons(130)
        .neutrons(234)
        .symbol("Nm")
    event.create("quadium")
        .protons(1)
        .neutrons(3)
        .symbol("Qd")
        .isIsotope(true)
    event.create("transcendental_matrix")
        .protons(6)
        .neutrons(32)
        .symbol("ᛝ")
})

GTCEuStartupEvents.registry("gtceu:material_icon_set", event => {
    event.create("crystal").parent(GTMaterialIconSet.SHINY)
    event.create("dilithium").parent(GTMaterialIconSet.DULL)
    event.create("eltz").parent(GTMaterialIconSet.SHINY)
    event.create("hyperdegenerate_matter").parent(GTMaterialIconSet.RADIOACTIVE)
    event.create("infinity").parent(GTMaterialIconSet.SHINY)
    event.create("mana").parent(GTMaterialIconSet.SHINY)
    event.create("monium").parent(GTMaterialIconSet.SHINY)
    event.create("necrosiderite").parent(GTMaterialIconSet.METALLIC)
    event.create("omnium").parent(GTMaterialIconSet.SHINY)
})

GTCEuStartupEvents.registry("gtceu:material", event => {
    event.create("cryococcus")
        .ingot().fluid()
        .element(GTElements.get("cryococcus"))
        .color(0x088286).secondaryColor(0x022C34).iconSet("metallic")
        .flags(GTMaterialFlags.NO_SMELTING, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME)

    event.create("cryolobus")
        .ingot().fluid()
        .element(GTElements.get("cryolobus"))
        .color(0x022C34).iconSet("metallic")
        .blastTemp(6800, "higher")
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_FRAME)
        .cableProperties(524288, 4, 0, true);

    event.create("crystal_matrix")
        .ingot().fluid()
        .element(GTElements.get("crystal_matrix"))
        .color(0x66ffff)
        .secondaryColor(0x004590)
        .blastTemp(3823, "highest", GTValues.VA[GTValues.ZPM])
        .iconSet("crystal")
        .fluidPipeProperties(4773, 1200, true, false, true, true)
        .flags(GTMaterialFlags.NO_WORKING, GTMaterialFlags.EXCLUDE_BLOCK_CRAFTING_RECIPES, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_ROTOR);

    event.create("dilithium")
        .dust()
        .gem()
        .ore(2, 1)
        .element(GTElements.get("dilithium"))
        .color(0xfdd2df).secondaryColor(0xfa52b5)
        .iconSet("dilithium")
        .addOreByproducts("lithium", "cobalt", "platinum")

    event.create("eltz")
        .ingot()
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .element(GTElements.get("eltz"))
        .color(0xffffff)
        .iconSet("eltz")
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_SPRING, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.PHOSPHORESCENT)

    event.create("hyperdegenerate_matter")
        .element(GTElements.get("hyperdegenerate_matter"))
        .color(0xffffff).iconSet("hyperdegenerate_matter")
        .liquid(new GTFluidBuilder().state(GTFluidState.PLASMA).customStill())

    event.create("infinity")
        .ingot()
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .element(GTElements.get("infinity"))
        .color(0xffffff)
        .iconSet("infinity")
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_DENSE, GTMaterialFlags.GENERATE_SMALL_GEAR)

    event.create("mana")
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .element(GTElements.get("mana"))
        .iconSet("mana")
        .flags(GTMaterialFlags.DISABLE_DECOMPOSITION)

    event.create("meta_null")
        .ingot()
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .color(0xffffff)
        .iconSet("meta_null")
        .element(GTElements.get("meta_null"))
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_FOIL, GTMaterialFlags.GENERATE_ROTOR)
        .fluidPipeProperties(15000, 1500, true, true, true, true)

    event.create("monium")
        .ingot()
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .element(GTElements.get("monium"))
        .color(0xffffff)
        .iconSet("monium")
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_ROD, GTMaterialFlags.GENERATE_FRAME, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_SPRING)
        .cableProperties(GTValues.V[GTValues.MAX], 134217727, 0, true)

    event.create("necrosiderite")
        .ingot()
        .color(0xffffff)
        .iconSet("necrosiderite")
        .flags(GTMaterialFlags.GENERATE_FINE_WIRE, GTMaterialFlags.GENERATE_SPRING)
        .cableProperties(33554432, 64, 8, false)
        .blastTemp(12200, "highest", 1000000, 1000)
        .element(GTElements.get("necrosiderite"))

    event.create("omnium")
        .ingot()
        .liquid(new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        .element(GTElements.get("omnium"))
        .color(0xffffff).iconSet("omnium")
        .flags(GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_SPRING)
        .cableProperties(GTValues.V[GTValues.UEV], 8, 8, false)

    event.create("quadium")
        .gas()
        .element(GTElements.get("quadium"))
        .color(0x7c5bff)

    event.create("transcendental_matrix")
        .ingot().fluid()
        .color(0xffffff).secondaryColor(0x000000)
        .iconSet("shiny")
        .element(GTElements.get("transcendental_matrix"))
        .flags(GTMaterialFlags.GENERATE_FOIL)
})
