name: Replace version
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  replace_manifest:
    name: Replace manifest version
    runs-on: ubuntu-latest
    steps:
      - run: sed -i s/\"version\":\ \"development\"/\"version\":\ \"${{ inputs.version }}\"/ manifest.json
        shell: bash
  
  # TODO: more jobs, like replacing version in the main menu